server:
  port: 9000
spring:
  cloud:
    # // 详细配置见https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-discovery
    nacos:
      discovery:
        enabled: true # 是否启动服务注册
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        ip: 127.0.0.1 # 指定当前实例注册时的ip，多网环境最好设置
        service: sample-consumer # 注册的服务名称，如果没有值则取${spring.application.name}
        cluster-name: shangHai
#  application:
#    name: sample-provider


sample-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.nbb.nacosDiscoveryConsumer.framework.ribbon.SameClusterPriorityRule
